# Generated by Django 4.1.2 on 2023-02-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default='', max_length=20, verbose_name=' Subject'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name=' Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.IntegerField(default=0),
        ),
    ]
