# Generated by Django 4.1.2 on 2023-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_created=True, auto_now=True)),
                ('userId', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('userContact', models.BigIntegerField()),
                ('address', models.TextField()),
                ('orderAmount', models.CharField(max_length=50)),
                ('paymentVia', models.CharField(default='', max_length=50)),
                ('paymentMethod', models.CharField(default=None, max_length=50)),
                ('transactionId', models.TextField(default=None)),
            ],
        ),
    ]
